version: "3.3"

services:

  mysql-db:
    image: mysql:5.6
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'devops'
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mynetwork
      

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin-container
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql-container
    networks:
      - mynetwork
      
  
  springboot-app:
    image: dorrahr/devopsrepository:latest
    container_name: springboot-app
   environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/devops?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: devops
    restart: on-failure
    ports:
      - 8089:8089 
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql: