version: "3.8"

services:

  db:
    image: mysql:latest
    restart: always
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'devops'
    ports:
      - 3306:3306
    networks:
      - mynetwork
    volumes:
      - mysql:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin-container
    ports:
      - 8090:80
    environment:
      PMA_HOST: db-container
    networks:
      - mynetwork

  springboot-app:
    image: dorrahr/devopsrepository:latest
    container_name: springboot-app
    environment:
      MYSQL_HOST: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'devops'
    ports:
      - 8089:8089
    links:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql:
